excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://domesticempire.github.io
title: exmessiah (he has risen, now he must nap)
email: retailonly@gmail.com
author: exmessiah
description: he has risen, now he must nap
paginate: 3
google_analytics: 
